"""them truong bill

Revision ID: 0e10c30000dc
Revises: 6c0a131bdfe5
Create Date: 2021-07-30 14:30:34.137727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e10c30000dc'
down_revision = '6c0a131bdfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('shop', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bill_detail_food_name'), ['food_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_detail_shop'), ['shop'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_detail_total'), ['total'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_detail_total'))
        batch_op.drop_index(batch_op.f('ix_bill_detail_shop'))
        batch_op.drop_index(batch_op.f('ix_bill_detail_food_name'))
        batch_op.drop_column('total')
        batch_op.drop_column('shop')
        batch_op.drop_column('food_name')

    # ### end Alembic commands ###
