"""tao bang 

Revision ID: 1c4152794a36
Revises: 
Create Date: 2021-07-23 22:33:42.485623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4152794a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pending', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_order_completed'), 'daily_order', ['completed'], unique=False)
    op.create_index(op.f('ix_daily_order_date'), 'daily_order', ['date'], unique=False)
    op.create_index(op.f('ix_daily_order_pending'), 'daily_order', ['pending'], unique=False)
    op.create_index(op.f('ix_daily_order_user_email'), 'daily_order', ['user_email'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_address'), 'shop', ['address'], unique=False)
    op.create_index(op.f('ix_shop_name'), 'shop', ['name'], unique=False)
    op.create_index(op.f('ix_shop_phone'), 'shop', ['phone'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_index(op.f('ix_food_price'), 'food', ['price'], unique=False)
    op.create_table('bill_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['order'], ['daily_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_detail_order_time'), 'bill_detail', ['order_time'], unique=False)
    op.create_index(op.f('ix_bill_detail_quantity'), 'bill_detail', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_detail_quantity'), table_name='bill_detail')
    op.drop_index(op.f('ix_bill_detail_order_time'), table_name='bill_detail')
    op.drop_table('bill_detail')
    op.drop_index(op.f('ix_food_price'), table_name='food')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_shop_phone'), table_name='shop')
    op.drop_index(op.f('ix_shop_name'), table_name='shop')
    op.drop_index(op.f('ix_shop_address'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_daily_order_user_email'), table_name='daily_order')
    op.drop_index(op.f('ix_daily_order_pending'), table_name='daily_order')
    op.drop_index(op.f('ix_daily_order_date'), table_name='daily_order')
    op.drop_index(op.f('ix_daily_order_completed'), table_name='daily_order')
    op.drop_table('daily_order')
    # ### end Alembic commands ###
