"""Tao thuoc tinh

Revision ID: 6c0a131bdfe5
Revises: 1c4152794a36
Create Date: 2021-07-29 14:42:41.399311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0a131bdfe5'
down_revision = '1c4152794a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_detail', schema=None) as batch_op:
        batch_op.drop_column('canceled')

    # ### end Alembic commands ###
