"""xoa total

Revision ID: a1c362ba7c96
Revises: f4333831df91
Create Date: 2021-08-18 00:51:44.092718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c362ba7c96'
down_revision = 'f4333831df91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_order', sa.Column('consolidation', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'daily_order', 'order_consolidation', ['consolidation'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_order', type_='foreignkey')
    op.drop_column('daily_order', 'consolidation')
    # ### end Alembic commands ###
