"""xoatotal

Revision ID: d8233604cb1b
Revises: 947920a65681
Create Date: 2021-08-18 00:57:48.069252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8233604cb1b'
down_revision = '947920a65681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_order', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_daily_order_consolidation_order_consolidation'), 'order_consolidation', ['consolidation'], ['id'])

    with op.batch_alter_table('order_consolidation', schema=None) as batch_op:
        batch_op.drop_index('ix_order_consolidation_total')
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_consolidation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_order_consolidation_total', ['total'], unique=False)

    with op.batch_alter_table('daily_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_order_consolidation_order_consolidation'), type_='foreignkey')

    # ### end Alembic commands ###
